/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_wuhaojie_demo_Demo */

#ifndef _Included_top_wuhaojie_demo_Demo
#define _Included_top_wuhaojie_demo_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_wuhaojie_demo_Demo
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_wuhaojie_demo_Demo_getString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
